include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: ['**/*.freezed.dart', '**/*.g.dart']
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    dead_code: error
    unused_import: error
    unused_element: ignore

linter:
  rules:
    - always_use_package_imports
    - always_put_required_named_parameters_first
    - avoid_bool_literals_in_conditional_expressions
    - avoid_redundant_argument_values
    - avoid_renaming_method_parameters
    - avoid_slow_async_io
    - avoid_unnecessary_containers
    - directives_ordering
    - eol_at_end_of_file
    - file_names
    - lines_longer_than_80_chars
    - matching_super_parameters
    - prefer_const_declarations
    - prefer_const_constructors
    - prefer_final_fields
    - prefer_final_locals
    - prefer_if_elements_to_conditional_expressions
    - prefer_if_null_operators
    - prefer_int_literals
    - prefer_null_aware_method_calls
    - prefer_null_aware_operators
    - prefer_single_quotes
    - prefer_spread_collections
    - require_trailing_commas
    - unnecessary_lambdas
    - use_colored_box
    - use_decorated_box
    - use_function_type_syntax_for_parameters
    - use_super_parameters
